# Generated by Django 2.2.3 on 2019-07-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dockerimage',
            name='downloaded',
            field=models.BooleanField(default=False),
        ),
    ]
